### ISSUE TITLE
Error: missing parameter response_type (required according to RFC)

### ISSUE THREAD

**Issue by hjacobs** [mrasband/aiohttp-oauth2#3]
Our IAM system does not accept the call to the Authorization URL as the `response_type` parameter is missing:
```
Error Code: invalid_request

Error Description: missing parameter response_type
```

This parameter is required according to RFC, see https://tools.ietf.org/html/rfc6749#section-3.1.1:

```
 If an authorization request is missing the "response_type" parameter,
   or if the response type is not understood, the authorization server
   MUST return an error response as described in Section 4.1.2.1.
```

**Comment by mattrasband** [comment]
I'll get to this after work today @hjacobs - I don't know how I missed that as I have implemented that a dozen times before finally writing this. Thank you!

**Comment by hjacobs** [comment]
@mrasband btw, I now switched to `aioauth_client` instead: https://codeberg.org/hjacobs/kube-web-view/src/branch/master/kube_web/web.py

**Comment by mattrasband** [comment]
:+1: I've not seen that, but great! My approach was just that I didn't like using middlewares for something apps should compose. But that's just a preference - glad that one works for you!
