### ISSUE TITLE
Twitter example?

### ISSUE THREAD

**Issue by mspanish** [mrasband/aiohttp-oauth2#8]
Hi I've tried using your Github example for Twitter, and haven't managed to get the token passing right to Twitter, so I get an error that the app hasn't send the token. Have you tried to do this with Twitter or have an example?  Thanks!

**Comment by mattrasband** [comment]
I’m out of town, but will be sure to test it when I’m home in a couple of days and let you know. I should set up a test site for all the contrib helpers.

**Comment by mspanish** [comment]
Thanks that would be great as your Github works like a charm :)

**Comment by mattrasband** [comment]
@mspanish I need to push an update to remove that, unfortunately twitter doesn't support OAuth2 for login (only oauth1) which is something that I currently don't plan to support. I plan to add some other examples along with a site to test that they all work soon. 

Sorry for misleading you with incorrectly including that as an option!
